[pytest]
pythonpath = .  # Allows imports relative to project root (e.g., from IEP.caption-generator.app)
testpaths = tests # Specifies where to find tests
addopts = -v -s --disable-warnings # Verbose, show prints, hide common warnings